### ISSUE TITLE
Browser Upload Delete

### ISSUE THREAD

**Issue by pyroprotectme** [romelgomez/angular-firebase-image-upload#1]
First off thanks for this git/repo,

Issues:
Finding the image is not displaying/rendering when viewing in multiple browsers open.
Example: open chorme, firefox and iPad safari. Navigate to https://ng-fire-image-upload.firebaseapp.com/#/ in all the 3 browsers.

Use chrome to upload image, image will only display on other chrome tabs. Firefox and iPad safari show text file name only and no image. Even refresh page does nothing.

Use firefox to upload image, image will show on all browsers.

Use iPad safari to upload image, image will show on all browsers.

Why would only chrome uploads not render on other browser / devices?

When removing images:
- The images do not remove from open cross browser windows. You must refresh to see the change.
-  Also in Firebase the publications>images>isDeleted: true but what about completely removing the deleted object to keep the database clutter down?

*also typo in app>styles>main.scss probably should be app>styles>main.css

**Comment by romelgomez** [comment]
Thanks for check the repo,  

I am currently using a much better solution:

http://cloudinary.com/

I save the images in cloudinary, then only save the id’s references in firebase. You firebase database will be smaller and inexpensive.

https://youtu.be/lI8zxSHsyR8?t=2m59s

This repository is no longer in maintenance. 

Best regards.

**Comment by pyroprotectme** [comment]
@romelgomez Thank you very much for the information and the better solution.
