### ISSUE TITLE
misclick

### ISSUE THREAD

**Issue by pyroprotectme** [romelgomez/angular-firebase-image-upload#2]

**Comment by romelgomez** [comment]
Skype: writingeveryday

I live in Venezuela.

**Comment by romelgomez** [comment]
btw i just saw this.

**Comment by pyroprotectme** [comment]
Thanks for replying, I sent you a skype invite. I watched your demo video,
the wep app looks great. Are you developing in ionic at all for mobile app?
Aslo do you plan to put your web app seen in the demo on git?
Paul Wong
USA Florida

**Comment by romelgomez** [comment]
Thanks, 

Already accepted your invitation.

Not yet, worked with ionic. 

No, that app is my startup, in the best case scenario i pretend get funds, or remote job opportunity. Soon i will send the app to http://inspire.co.uk/venture/ to review.

If you want to see my resume, send me your e-mail.

Best regards.

**Comment by pyroprotectme** [comment]
Email is diveloperinc@gmail.com

Also I have plans to build a very similar web app in the US. The demo you
have, is it built all in AngularFire? or are you using NodeJS?

Paul
